name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.13.2  # Or your preferred Python version
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Install pytest explicitly if not in requirements.txt
      - name: Run tests
        run: pytest